language: java

services:
    - mysql

before_install:
    - echo "Configuring build."
    #Change into directory where pom.xml is located
    - cd LSDProjectBackend
    #Change mysql password to match local development config (from travis docs),
    - sudo mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root');"
    - sudo service mysql restart
    #Create database with new credentials
    - sudo mysql -u root -proot -e "CREATE DATABASE lsd;"